Add reduction of rules by coverage
knodle/knodle pull request #278
Opened 2021-05-26 12:04 UTC by marina-sp

closes #277

2021-05-26 12:10 UTC, marina-sp commented
This can be used for making the dataset smaller wrt the number of rules. E.g. I intend to use it for Tacred where there are too many rules for Snorkel to handle. A (hopefully) detailed description of the reduction process is provided in the code comments.

I am not sure about the placement of this function, since it should be mostly used for data preprocessing prior to passing it to a Trainer. Then it would make sense to place it in the experiments.utils or similar. However, we could include this reduction into the Snorkel Trainer itself to ensure the data is reasonably sized before calling the LabelModel. Then it is appropriate to leave this functionality in transformations (as it is now). I would appreciate your thoughts on this :)

2021-05-26 13:31 UTC, agsedova requested changes

2021-05-26 13:31 UTC, agsedova commented on knodle/transformation/rule_reduction.py
> +    if max_rules is not None:
to be sure: is it a valid use case when user wants both filtering by max rules and coverage?

2021-05-26 13:31 UTC, agsedova commented on knodle/transformation/rule_reduction.py
> +def _reduce_by_drop(rule_matches_dict, mapping_rule_class_t, lf_kept_mask):
typing and output please :) a couple of comment words would also be good

2021-05-26 13:31 UTC, agsedova commented on knodle/transformation/rule_reduction.py
> +def _reduce_by_merge(rule_matches_dict, mapping_rule_class_t, lf_kept_mask):
typing and output

2021-05-26 13:31 UTC, agsedova commented on knodle/transformation/rule_reduction.py
> +    Get an iterator yielding an rule ids mask for every label, indicating which rules belong to this label.
an -> a

2021-05-26 13:31 UTC, agsedova commented on knodle/transformation/rule_reduction.py
> +    Get an iterator yielding an rule ids mask for every label, indicating which rules belong to this label.
btw there is a function `get_rules_sample_ids` in knodle/trainer/wscrossweigh - I guess it is done pretty much the same, but not exactly.

2021-05-26 13:35 UTC, agsedova commented
> I am not sure about the placement of this function, since it should be mostly used for data preprocessing prior to passing it to a Trainer. Then it would make sense to place it in the experiments.utils or similar. However, we could include this reduction into the Snorkel Trainer itself to ensure the data is reasonably sized before calling the LabelModel. Then it is appropriate to leave this functionality in transformations (as it is now). I would appreciate your thoughts on this :)

I don't think it should be a part of `experiments.utils` or whatever, but a part of the knodle core. Totally fine with where it is located now, in`transformations`.

2021-07-04 13:18 UTC, agsedova approved these changes

2021-07-04 13:19 UTC, merged